//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortalMvc.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE
    {
        public string TYPECD { get; set; }
        public string CODECD { get; set; }
        public string CODENAME { get; set; }
        public Nullable<byte> MARK { get; set; }
        public Nullable<bool> FIXEDYN { get; set; }
    }
}
