//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortalMvc.DBEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbPOR : DbContext
    {
        public DbPOR()
            : base("name=DbPOR")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BbsContent> BbsContent { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<OvertimeForm> OvertimeForm { get; set; }
        public virtual DbSet<SalaryLimit> SalaryLimit { get; set; }
        public virtual DbSet<SignAgent> SignAgent { get; set; }
        public virtual DbSet<SignDocCode> SignDocCode { get; set; }
        public virtual DbSet<SignForm_Detail> SignForm_Detail { get; set; }
        public virtual DbSet<SignForm_Log> SignForm_Log { get; set; }
        public virtual DbSet<SignForm_Main> SignForm_Main { get; set; }
        public virtual DbSet<SignProcedure> SignProcedure { get; set; }
        public virtual DbSet<SignType> SignType { get; set; }
        public virtual DbSet<SysGroup> SysGroup { get; set; }
        public virtual DbSet<SystemArchitecture> SystemArchitecture { get; set; }
        public virtual DbSet<ForgotPunchForm> ForgotPunchForm { get; set; }
        public virtual DbSet<PeriodType> PeriodType { get; set; }
        public virtual DbSet<UserPriority> UserPriority { get; set; }
    }
}
