//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortalMvc.DBEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbTRAIN : DbContext
    {
        public DbTRAIN()
            : base("name=DbTRAIN")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public virtual DbSet<CENTER> CENTER { get; set; }
        public virtual DbSet<CHARACTER_ANSWER> CHARACTER_ANSWER { get; set; }
        public virtual DbSet<CODE> CODE { get; set; }
        public virtual DbSet<CODEMST> CODEMST { get; set; }
        public virtual DbSet<FORM_FORMAT> FORM_FORMAT { get; set; }
        public virtual DbSet<FORM_RECORDS> FORM_RECORDS { get; set; }
        public virtual DbSet<FORM_SIGN> FORM_SIGN { get; set; }
        public virtual DbSet<NUMERIC_ANSWER> NUMERIC_ANSWER { get; set; }
        public virtual DbSet<QUESTIONS> QUESTIONS { get; set; }
        public virtual DbSet<REQUIRE> REQUIRE { get; set; }
        public virtual DbSet<RTCLASS> RTCLASS { get; set; }
        public virtual DbSet<RTCLASS_TEXT> RTCLASS_TEXT { get; set; }
        public virtual DbSet<STUDENTS> STUDENTS { get; set; }
        public virtual DbSet<TEACHER> TEACHER { get; set; }
        public virtual DbSet<TEACHER_GROUP> TEACHER_GROUP { get; set; }
        public virtual DbSet<form_records_tmp> form_records_tmp { get; set; }
        public virtual DbSet<students_temp> students_temp { get; set; }
    }
}
