//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortalMvc.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORM_SIGN
    {
        public string CLID { get; set; }
        public string SID { get; set; }
        public string TABLE_ID { get; set; }
        public string SignDocID { get; set; }
        public bool IsSigned { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Edit_Person { get; set; }
    }
}
