//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortalMvc.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUIRE
    {
        public int REQID { get; set; }
        public string CLNAME0 { get; set; }
        public string UNITID { get; set; }
        public string UNITNAME { get; set; }
        public Nullable<short> REQYEAR { get; set; }
        public string MEMO { get; set; }
        public string CTID { get; set; }
        public string CLTYPE { get; set; }
        public Nullable<decimal> HOURS0 { get; set; }
        public Nullable<byte> PREMONTH0 { get; set; }
        public string TARGET_PEOPLE { get; set; }
        public string TARGET_TITLE { get; set; }
        public Nullable<byte> NUM_PEOPLE0 { get; set; }
        public string PURPOSE { get; set; }
        public Nullable<byte> KID0 { get; set; }
        public string KIND0 { get; set; }
        public Nullable<int> BUDGET { get; set; }
        public Nullable<byte> CATEGORY { get; set; }
        public Nullable<bool> APPROVE { get; set; }
        public bool DISABLED { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
        public string EDIT_PERSON { get; set; }
    }
}
