//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortalMvc.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RTCLASS
    {
        public string CLID { get; set; }
        public Nullable<int> REQID { get; set; }
        public string CLNAME0 { get; set; }
        public string CLNAME { get; set; }
        public string UNITID { get; set; }
        public string UNITNAME { get; set; }
        public Nullable<short> REQYEAR { get; set; }
        public string MEMO { get; set; }
        public string CTID0 { get; set; }
        public string CLTYPE0 { get; set; }
        public string CTID { get; set; }
        public string CLTYPE { get; set; }
        public Nullable<decimal> HOURS0 { get; set; }
        public Nullable<decimal> HOURS { get; set; }
        public Nullable<byte> PREMONTH0 { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string START_TIME { get; set; }
        public string END_TIME { get; set; }
        public string TARGET_PEOPLE0 { get; set; }
        public string TARGET_PEOPLE { get; set; }
        public string TARGET_TITLE0 { get; set; }
        public string TARGET_TITLE { get; set; }
        public Nullable<byte> NUM_PEOPLE0 { get; set; }
        public Nullable<byte> NUM_PEOPLE { get; set; }
        public string PURPOSE0 { get; set; }
        public string PURPOSE { get; set; }
        public Nullable<byte> KID0 { get; set; }
        public string KIND0 { get; set; }
        public Nullable<byte> KID { get; set; }
        public string KIND { get; set; }
        public Nullable<byte> BID { get; set; }
        public Nullable<int> FEE0 { get; set; }
        public Nullable<int> FEE { get; set; }
        public string REASON { get; set; }
        public Nullable<byte> PAYID { get; set; }
        public string PAY_TYPE { get; set; }
        public Nullable<byte> FEESID { get; set; }
        public string FEE_STATUS { get; set; }
        public Nullable<byte> CATEID0 { get; set; }
        public Nullable<byte> CATEID { get; set; }
        public string DUTYTIME { get; set; }
        public string CID { get; set; }
        public string ADDRESS { get; set; }
        public string TID { get; set; }
        public Nullable<byte> RESULT { get; set; }
        public Nullable<byte> STATUS { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
        public string EDIT_PERSON { get; set; }
        public Nullable<bool> DISABLED { get; set; }
    }
}
