//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortalMvc.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignForm_Main
    {
        public SignForm_Main()
        {
            this.SignForm_Detail = new HashSet<SignForm_Detail>();
        }
    
        public string SignDocID { get; set; }
        public int FormID_FK { get; set; }
        public string EmployeeID_FK { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public string CurrentSignLevelDeptID_FK { get; set; }
        public int FinalStatus { get; set; }
        public int Remainder { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Modifier { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<SignForm_Detail> SignForm_Detail { get; set; }
        public virtual SignType SignType { get; set; }
    }
}
