//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortalMvc.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENTS
    {
        public string SID { get; set; }
        public string CLID { get; set; }
        public string CLNAME { get; set; }
        public string SNAME { get; set; }
        public string TITLE { get; set; }
        public string UNITID { get; set; }
        public string UNITNAME { get; set; }
        public string CURRENT_BOSS { get; set; }
        public Nullable<bool> DUTY { get; set; }
        public string CERT_NUM { get; set; }
        public Nullable<System.DateTime> EDIT_DATE { get; set; }
        public string EDIT_PERSON { get; set; }
    }
}
