//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class B0401D
    {
        public decimal B0401DSN { get; set; }
        public string MAllowanceNumber { get; set; }
        public string DOriginalInvoiceDate { get; set; }
        public string DOriginalInvoiceNumber { get; set; }
        public string DOriginalSequenceNumber { get; set; }
        public string DOriginalDescription { get; set; }
        public string DQuantity { get; set; }
        public string DUnit { get; set; }
        public string DUnitPrice { get; set; }
        public string DAmount { get; set; }
        public string DTax { get; set; }
        public string DAllowanceSequenceNumber { get; set; }
        public string DTaxType { get; set; }
        public Nullable<System.DateTime> DataTime { get; set; }
        public string TxFileNmae { get; set; }
        public string ExXmlYN { get; set; }
        public Nullable<System.DateTime> ExXmlTime { get; set; }
    }
}
