//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class B0401H
    {
        public decimal B0401SN { get; set; }
        public string MAllowanceNumber { get; set; }
        public string MAllowanceDate { get; set; }
        public string MSIdentifier { get; set; }
        public string MSName { get; set; }
        public string MSAddress { get; set; }
        public string MSPersonInCharge { get; set; }
        public string MSTelephoneNumber { get; set; }
        public string MSFacsimileNumber { get; set; }
        public string MSEmailAddress { get; set; }
        public string MSCustomerNumber { get; set; }
        public string MSRoleRemark { get; set; }
        public string MBIdentifier { get; set; }
        public string MBName { get; set; }
        public string MBAddress { get; set; }
        public string MBPersonInCharge { get; set; }
        public string MBTelephoneNumber { get; set; }
        public string MBFacsimileNumber { get; set; }
        public string MBEmailAddress { get; set; }
        public string MBCustomerNumber { get; set; }
        public string MBRoleRemark { get; set; }
        public string MAllowanceType { get; set; }
        public string ATaxAmount { get; set; }
        public string ATotalAmount { get; set; }
        public Nullable<System.DateTime> DataTime { get; set; }
        public string TxFileNmae { get; set; }
        public string ExXmlYN { get; set; }
        public string ExPdfYN { get; set; }
    }
}
