//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C0401H
    {
        public decimal C0401SN { get; set; }
        public string MInvoiceNumber { get; set; }
        public string MInvoiceDate { get; set; }
        public string MInvoiceTime { get; set; }
        public string MSIdentifier { get; set; }
        public string MSName { get; set; }
        public string MSAddress { get; set; }
        public string MSPersonInCharge { get; set; }
        public string MSTelephoneNumber { get; set; }
        public string MSFacsimileNumber { get; set; }
        public string MSEmailAddress { get; set; }
        public string MSCustomerNumber { get; set; }
        public string MSRoleRemark { get; set; }
        public string MBIdentifier { get; set; }
        public string MBName { get; set; }
        public string MBAddress { get; set; }
        public string MBPersonInCharge { get; set; }
        public string MBTelephoneNumber { get; set; }
        public string MBFacsimileNumber { get; set; }
        public string MBEmailAddress { get; set; }
        public string MBCustomerNumber { get; set; }
        public string MBRoleRemark { get; set; }
        public string MCheckNumber { get; set; }
        public string MBuyerRemark { get; set; }
        public string MMainRemark { get; set; }
        public string MCustomsClearanceMark { get; set; }
        public string MCategory { get; set; }
        public string MRelateNumber { get; set; }
        public string MInvoiceType { get; set; }
        public string MGroupMark { get; set; }
        public string MDonateMark { get; set; }
        public string MCarrierType { get; set; }
        public string MCarrierId1 { get; set; }
        public string MCarrierId2 { get; set; }
        public string MPrintMark { get; set; }
        public string MNPOBAN { get; set; }
        public string MRandomNumber { get; set; }
        public string ASalesAmount { get; set; }
        public string AFreeTaxSalesAmount { get; set; }
        public string AZeroTaxSalesAmount { get; set; }
        public string ATaxType { get; set; }
        public string ATaxRate { get; set; }
        public string ATaxAmount { get; set; }
        public string ATotalAmount { get; set; }
        public string ADiscountAmount { get; set; }
        public string AOriginalCurrencyAmount { get; set; }
        public string AExchangeRate { get; set; }
        public string ACurrency { get; set; }
        public System.DateTime DataTime { get; set; }
        public string TxFileNmae { get; set; }
        public string ExXmlYN { get; set; }
        public string ExPdfYN { get; set; }
    }
}
