//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class D0501
    {
        public decimal D0501SN { get; set; }
        public string CancelAllowanceNumber { get; set; }
        public string AllowanceDate { get; set; }
        public string BuyerId { get; set; }
        public string SellerId { get; set; }
        public string CancelDate { get; set; }
        public string CancelTime { get; set; }
        public string CancelReason { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DataTime { get; set; }
        public string TxFileNmae { get; set; }
        public string ExXmlYN { get; set; }
        public Nullable<System.DateTime> ExXmlTime { get; set; }
    }
}
