//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortal.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPDB : DbContext
    {
        public ERPDB()
            : base("name=ERPDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rinnai_Sales_Invoice_Line> Rinnai_Sales_Invoice_Line { get; set; }
        public virtual DbSet<Rinnai_Service_Ledger_Entry> Rinnai_Service_Ledger_Entry { get; set; }
    }
}
