//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortal.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbINV : DbContext
    {
        public DbINV()
            : base("name=DbINV")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A0401D> A0401D { get; set; }
        public virtual DbSet<A0401H> A0401H { get; set; }
        public virtual DbSet<A0501> A0501 { get; set; }
        public virtual DbSet<A0601> A0601 { get; set; }
        public virtual DbSet<B0401D> B0401D { get; set; }
        public virtual DbSet<B0401H> B0401H { get; set; }
        public virtual DbSet<B0501> B0501 { get; set; }
        public virtual DbSet<C0401D> C0401D { get; set; }
        public virtual DbSet<C0401H> C0401H { get; set; }
        public virtual DbSet<C0501> C0501 { get; set; }
        public virtual DbSet<C0701> C0701 { get; set; }
        public virtual DbSet<D0401D> D0401D { get; set; }
        public virtual DbSet<D0401H> D0401H { get; set; }
        public virtual DbSet<D0501> D0501 { get; set; }
        public virtual DbSet<SParameter> SParameter { get; set; }
        public virtual DbSet<STemp> STemp { get; set; }
    }
}
