//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortal.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBISO : DbContext
    {
        public DBISO()
            : base("name=DBISO")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IsoFiles> IsoFiles { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<IsoMain> IsoMain { get; set; }
        public virtual DbSet<IsoFileLog> IsoFileLog { get; set; }
        public virtual DbSet<IsoFileSetting> IsoFileSetting { get; set; }
        public virtual DbSet<IsoPublishGroup> IsoPublishGroup { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
    }
}
