//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsoFileSetting
    {
        public int ID { get; set; }
        public int MAP_FILE_ID { get; set; }
        public int REF_DOC_ID { get; set; }
        public string REF_ISO_NUM { get; set; }
        public string NM_OF_PRODT { get; set; }
        public int TAKE_ON_DEP_ID { get; set; }
        public System.DateTime EFF_DT { get; set; }
        public string VERSION { get; set; }
        public string PAGE { get; set; }
    }
}
