//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsoFiles
    {
        public int ID { get; set; }
        public int MAP_MAIN_ID { get; set; }
        public string FILE_PATH { get; set; }
        public System.DateTime BUD_DT { get; set; }
        public string REF_ISO_NUM { get; set; }
        public string FILE_NM { get; set; }
        public double FILE_SZ { get; set; }
        public string URL_PATH { get; set; }
        public string UP_MODE { get; set; }
    }
}
