//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsoMain
    {
        public int ID { get; set; }
        public string APP_USR { get; set; }
        public System.DateTime APP_DT { get; set; }
        public string APP_ST { get; set; }
        public System.DateTime APP_UP_DT { get; set; }
        public string ISO_NUM { get; set; }
        public Nullable<int> DOC_LEVEL { get; set; }
        public string REMARK { get; set; }
    }
}
