//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RinnaiPortal.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rinnai_Sales_Invoice_Line
    {
        public byte[] timestamp { get; set; }
        public string Document_No_ { get; set; }
        public int Line_No_ { get; set; }
        public string Sell_to_Customer_No_ { get; set; }
        public int Type { get; set; }
        public string No_ { get; set; }
        public string Location_Code { get; set; }
        public string Posting_Group { get; set; }
        public System.DateTime Shipment_Date { get; set; }
        public string Description { get; set; }
        public string Description_2 { get; set; }
        public string Unit_of_Measure { get; set; }
        public decimal Quantity { get; set; }
        public decimal Unit_Price { get; set; }
        public decimal Unit_Cost__LCY_ { get; set; }
        public decimal VAT__ { get; set; }
        public decimal Line_Discount__ { get; set; }
        public decimal Line_Discount_Amount { get; set; }
        public decimal Amount { get; set; }
        public decimal Amount_Including_VAT { get; set; }
        public byte Allow_Invoice_Disc_ { get; set; }
        public decimal Gross_Weight { get; set; }
        public decimal Net_Weight { get; set; }
        public decimal Units_per_Parcel { get; set; }
        public decimal Unit_Volume { get; set; }
        public int Appl__to_Item_Entry { get; set; }
        public string Shortcut_Dimension_1_Code { get; set; }
        public string Shortcut_Dimension_2_Code { get; set; }
        public string Customer_Price_Group { get; set; }
        public string Job_No_ { get; set; }
        public int Appl__to_Job_Entry { get; set; }
        public string Phase_Code { get; set; }
        public string Task_Code { get; set; }
        public string Step_Code { get; set; }
        public string Job_Applies_to_ID { get; set; }
        public byte Apply_and_Close__Job_ { get; set; }
        public string Work_Type_Code { get; set; }
        public string Shipment_No_ { get; set; }
        public int Shipment_Line_No_ { get; set; }
        public string Bill_to_Customer_No_ { get; set; }
        public decimal Inv__Discount_Amount { get; set; }
        public byte Drop_Shipment { get; set; }
        public string Gen__Bus__Posting_Group { get; set; }
        public string Gen__Prod__Posting_Group { get; set; }
        public int VAT_Calculation_Type { get; set; }
        public string Transaction_Type { get; set; }
        public string Transport_Method { get; set; }
        public int Attached_to_Line_No_ { get; set; }
        public string Exit_Point { get; set; }
        public string Area { get; set; }
        public string Transaction_Specification { get; set; }
        public string Tax_Area_Code { get; set; }
        public byte Tax_Liable { get; set; }
        public string Tax_Group_Code { get; set; }
        public string VAT_Bus__Posting_Group { get; set; }
        public string VAT_Prod__Posting_Group { get; set; }
        public string Blanket_Order_No_ { get; set; }
        public int Blanket_Order_Line_No_ { get; set; }
        public decimal VAT_Base_Amount { get; set; }
        public decimal Unit_Cost { get; set; }
        public byte System_Created_Entry { get; set; }
        public decimal Line_Amount { get; set; }
        public decimal VAT_Difference { get; set; }
        public string VAT_Identifier { get; set; }
        public int IC_Partner_Ref__Type { get; set; }
        public string IC_Partner_Reference { get; set; }
        public string Variant_Code { get; set; }
        public string Bin_Code { get; set; }
        public decimal Qty__per_Unit_of_Measure { get; set; }
        public string Unit_of_Measure_Code { get; set; }
        public decimal Quantity__Base_ { get; set; }
        public System.DateTime FA_Posting_Date { get; set; }
        public string Depreciation_Book_Code { get; set; }
        public byte Depr__until_FA_Posting_Date { get; set; }
        public string Duplicate_in_Depreciation_Book { get; set; }
        public byte Use_Duplication_List { get; set; }
        public string Responsibility_Center { get; set; }
        public string Cross_Reference_No_ { get; set; }
        public string Unit_of_Measure__Cross_Ref__ { get; set; }
        public int Cross_Reference_Type { get; set; }
        public string Cross_Reference_Type_No_ { get; set; }
        public string Item_Category_Code { get; set; }
        public byte Nonstock { get; set; }
        public string Purchasing_Code { get; set; }
        public string Product_Group_Code { get; set; }
        public int Appl__from_Item_Entry { get; set; }
        public string Service_Contract_No_ { get; set; }
        public string Service_Order_No_ { get; set; }
        public string Service_Item_No_ { get; set; }
        public int Appl__to_Service_Entry { get; set; }
        public int Service_Item_Line_No_ { get; set; }
        public string Serv__Price_Adjmt__Gr__Code { get; set; }
        public string Return_Reason_Code { get; set; }
        public byte Allow_Line_Disc_ { get; set; }
        public string Customer_Disc__Group { get; set; }
        public string Short_Dimension_3 { get; set; }
        public byte Session_discount { get; set; }
        public byte Yearly_disount { get; set; }
        public int Contract_type { get; set; }
        public string Contract_no_ { get; set; }
        public int Basic_contract { get; set; }
        public string Dealer_Item_No_ { get; set; }
        public string Base_VAT_Transaction_Number { get; set; }
        public int Base_Return_Seq__No_ { get; set; }
        public int Base_Line_Number { get; set; }
        public string VAT_Transaction_Number { get; set; }
        public int Return_Seq__No_ { get; set; }
        public int Line_Number { get; set; }
        public int Contract_ine_No_ { get; set; }
        public int Group_ID { get; set; }
        public int Start_Serial_Number { get; set; }
        public string Lot_Number { get; set; }
        public byte VIP { get; set; }
    }
}
